export const ROLES = {
  ADMIN: 'admin',
  MANAGER: 'manager',
  USER: 'user',
};

export const PERMISSIONS = {
  CREATE_INVOICE: 'create:invoice',
  READ_INVOICE: 'read:invoice',
  UPDATE_INVOICE: 'update:invoice',
  DELETE_INVOICE: 'delete:invoice',
  MANAGE_USERS: 'manage:users',
  MANAGE_CUSTOMERS: 'manage:customers',
  VIEW_REPORTS: 'view:reports',
};

export const ROLE_PERMISSIONS = {
  [ROLES.ADMIN]: [
    PERMISSIONS.CREATE_INVOICE,
    PERMISSIONS.READ_INVOICE,
    PERMISSIONS.UPDATE_INVOICE,
    PERMISSIONS.DELETE_INVOICE,
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.MANAGE_CUSTOMERS,
    PERMISSIONS.VIEW_REPORTS,
  ],
  [ROLES.MANAGER]: [
    PERMISSIONS.CREATE_INVOICE,
    PERMISSIONS.READ_INVOICE,
    PERMISSIONS.UPDATE_INVOICE,
    PERMISSIONS.MANAGE_CUSTOMERS,
    PERMISSIONS.VIEW_REPORTS,
  ],
  [ROLES.USER]: [
    PERMISSIONS.CREATE_INVOICE,
    PERMISSIONS.READ_INVOICE,
    PERMISSIONS.UPDATE_INVOICE,
  ],
};
