export const ROLES = {
  ADMIN: 'admin',
  MANAGER: 'manager',
  USER: 'user',
};

export const PERMISSIONS = {
  CREATE_INVOICE: 'create_invoice',
  READ_INVOICE: 'read_invoice',
  UPDATE_INVOICE: 'update_invoice',
  DELETE_INVOICE: 'delete_invoice',
  VIEW_REPORTS: 'view_reports',
  MANAGE_USERS: 'manage_users',
  MANAGE_SETTINGS: 'manage_settings',
};

export const ROLE_PERMISSIONS = {
  [ROLES.ADMIN]: [
    PERMISSIONS.CREATE_INVOICE,
    PERMISSIONS.READ_INVOICE,
    PERMISSIONS.UPDATE_INVOICE,
    PERMISSIONS.DELETE_INVOICE,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.MANAGE_SETTINGS,
  ],
  [ROLES.MANAGER]: [
    PERMISSIONS.CREATE_INVOICE,
    PERMISSIONS.READ_INVOICE,
    PERMISSIONS.UPDATE_INVOICE,
    PERMISSIONS.DELETE_INVOICE,
    PERMISSIONS.VIEW_REPORTS,
  ],
  [ROLES.USER]: [
    PERMISSIONS.CREATE_INVOICE,
    PERMISSIONS.READ_INVOICE,
    PERMISSIONS.UPDATE_INVOICE,
  ],
};
